#Assignment_customer
#......................................
import numpy as np
import pandas as pd
df=pd.read_csv('/home/ubaid/Downloads/customer1.txt',header=None)
df.columns=['id','fname','lname','age','prof','loc']
print(df)
df1=df.fillna('india')
print(df1.isna().sum())
#1)
print(df1.shape[0])
#2)
print(df1.drop_duplicates().shape[0])
#3)
df2=df1.sort_values(by='age',ascending=False) [['fname','lname','prof','loc']].head(10)
print(df2)
#4)
df3=df1.sort_values(by='age') [['fname','lname','prof','loc']].head(5)
print(df3)
#5)
df4=df1.groupby('loc') ['loc'].count().sort_values(ascending=False)
print(df4)
#6)
df5=df1.loc[df1['loc']=='australia']
print(df5)
#7)
df6=df1.groupby('age') ['age'].count().sort_values(ascending=False)
print(df6)
#8)
df7=df1.groupby('prof') ['prof'].count().sort_values(ascending=False)
print(df7)
#9)
df8=df1.loc[df['loc']=='india']
print(df8)
#9A)
print(df8.shape[0])
#9B)
df9=df8.groupby('prof') ['prof'].count().sort_values(ascending=False)
print(df9)
#9C)
df10=df8.sort_values(by='age',ascending=False) [['fname','lname','age','prof']].head(3)
print(df10)
#9D)
df11=df8.sort_values(by='age') [['fname','lname','age','prof']].head(3)
print(df11)
#9E)
df12=df8.loc[df8['age']>40]
print(df12)
#9F)
df13=df8.loc[(df8['age']>30)&(df8['age']<40)].groupby('prof') ['prof'].count()
print(df13)
#10)
df14=df1.loc[df1['loc']=='us']
print(df14)
#10A)
print(df14.shape[0])
#10B)
df15=df14.groupby('age') ['age'].count()
print(df15)
#10C)
df16=df14.groupby('prof') ['prof'].count().sort_values(ascending=False)
print(df16)
#10D)
df17=df14.loc[(df14['prof']=='Civil engineer')&(df14['age']>30)]
print(df17)